version: "0.0"
services:
    database:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: papan_bunga
            MYSQL_USER: root
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3307:3307'
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
