version: "0.0"
services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: papan_bunga
            MYSQL_USER: user
            MYSQL_PASSWORD: dbpassword
            MYSQL_ROOT_PASSWORD: dbpassword
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
